# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/master.xdc

# Block Designs: bd/CPU/CPU.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU || ORIG_REF_NAME==CPU} -quiet] -quiet

# IP: bd/CPU/ip/CPU_processing_system7_0_0/CPU_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_processing_system7_0_0 || ORIG_REF_NAME==CPU_processing_system7_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_proc_sys_reset_0_0/CPU_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_proc_sys_reset_0_0 || ORIG_REF_NAME==CPU_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_axi_interconnect_0_imp_xbar_0/CPU_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==CPU_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_axi_interconnect_0_0/CPU_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_axi_interconnect_0_0 || ORIG_REF_NAME==CPU_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_axi_gpio_0_0/CPU_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_axi_gpio_0_0 || ORIG_REF_NAME==CPU_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_blk_mem_gen_0_0/CPU_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_blk_mem_gen_0_0 || ORIG_REF_NAME==CPU_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_axi_bram_ctrl_0_0/CPU_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_axi_bram_ctrl_0_0 || ORIG_REF_NAME==CPU_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_axi_interconnect_0_imp_auto_pc_1/CPU_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==CPU_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/CPU/ip/CPU_axi_interconnect_0_imp_auto_pc_0/CPU_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==CPU_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/germa/Documents/projects/FPGA/New folder/oscilloscope/oscilloscope.gen/sources_1/bd/CPU/CPU_ooc.xdc
