# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/germa/Documents/projects/FPGA/New folder/oscilloscope/oscilloscope.srcs/sources_1/bd/CPU/ip/CPU_axi_interconnect_0_imp_xbar_0/CPU_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'CPU_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/germa/Documents/projects/FPGA/New folder/oscilloscope/oscilloscope.gen/sources_1/bd/CPU/ip/CPU_axi_interconnect_0_imp_xbar_0/CPU_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/germa/Documents/projects/FPGA/New folder/oscilloscope/oscilloscope.srcs/sources_1/bd/CPU/ip/CPU_axi_interconnect_0_imp_xbar_0/CPU_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'CPU_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/germa/Documents/projects/FPGA/New folder/oscilloscope/oscilloscope.gen/sources_1/bd/CPU/ip/CPU_axi_interconnect_0_imp_xbar_0/CPU_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
